package app

import (
	"context"
	"database/sql"
	"fmt"

	"github.com/nickZFZ/Sydom/sdk/go/sydom"
	"github.com/nickZFZ/Sydom/sdk/go/sydomsql"
)

// Order 是一条订单（订单服务自有业务数据，与司域权限数据无关）。
type Order struct {
	ID       int64
	Customer string
	Amount   int64
	Dept     string // 数据权限按此列做行级过滤（对应数据策略 condition 的 field=dept）
}

// EnsureSchema 幂等建 orders 表（demo：业务方自有库自有表）。
func EnsureSchema(ctx context.Context, db *sql.DB) error {
	_, err := db.ExecContext(ctx, `
CREATE TABLE IF NOT EXISTS orders (
	id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	customer TEXT   NOT NULL,
	amount   BIGINT NOT NULL,
	dept     TEXT   NOT NULL
)`)
	return err
}

// SeedOrders 幂等播种跨部门订单（空表才插）。
func SeedOrders(ctx context.Context, db *sql.DB) error {
	var n int
	if err := db.QueryRowContext(ctx, `SELECT count(*) FROM orders`).Scan(&n); err != nil {
		return err
	}
	if n > 0 {
		return nil
	}
	_, err := db.ExecContext(ctx, `
INSERT INTO orders (customer, amount, dept) VALUES
	('上海客户A', 100, 'shanghai'),
	('上海客户B', 200, 'shanghai'),
	('上海客户C', 300, 'shanghai'),
	('北京客户A', 400, 'beijing'),
	('北京客户B', 500, 'beijing'),
	('北京客户C', 600, 'beijing')`)
	return err
}

// ListOrders 按数据权限片段 fr（来自 sydom.Client.FilterSQL）过滤订单。
// 三态由 sydomsql.Build 归一：MatchAll 不附 WHERE；MatchNone 附 "1=0"（deny-all 绝不退化）；
// Conditional 附改写后的 $N 片段 + 实参。
func ListOrders(ctx context.Context, db *sql.DB, fr sydom.FilterResult) ([]Order, error) {
	clause, err := sydomsql.Build(fr, sydomsql.Postgres, 0)
	if err != nil {
		return nil, err // fail-close：拿不到合法片段不查
	}
	q := `SELECT id, customer, amount, dept FROM orders`
	var args []any
	switch clause.Kind {
	case sydomsql.MatchAll:
		// 无行过滤
	case sydomsql.MatchNone:
		q += ` WHERE ` + clause.SQL
	case sydomsql.Conditional:
		q += ` WHERE ` + clause.SQL
		args = clause.Args
	default:
		// 防御性 fail-close：未知 Kind 宁可不查也绝不退化为全表。
		return nil, fmt.Errorf("orderservice: 未知 sydomsql.Clause.Kind=%d", clause.Kind)
	}
	q += ` ORDER BY id`
	rows, err := db.QueryContext(ctx, q, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var out []Order
	for rows.Next() {
		var o Order
		if err := rows.Scan(&o.ID, &o.Customer, &o.Amount, &o.Dept); err != nil {
			return nil, err
		}
		out = append(out, o)
	}
	return out, rows.Err()
}

// DeleteOrder 删一行，返回是否删到。
func DeleteOrder(ctx context.Context, db *sql.DB, id int64) (bool, error) {
	res, err := db.ExecContext(ctx, `DELETE FROM orders WHERE id=$1`, id)
	if err != nil {
		return false, err
	}
	n, err := res.RowsAffected()
	if err != nil {
		return false, err
	}
	return n > 0, nil
}
