{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sydom-controlplane.serviceAccountName" . }}
  labels:
    {{- include "sydom-controlplane.labels" . | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
